### ISSUE TITLE
EmpoweredFinanceV.1


### ISSUE THREAD

**Issue by tobiasarch1993** [graphprotocol/graph-client#708]
yarn add -D @graphprotocol/client-cli
# or, with NPM:
npm install --save-dev @graphprotocol/client-cli
```[tasklist]
### Tasks
- [ ] https://github.com/graphprotocol/graph-client/issues/23
- [ ] https://github.com/graphprotocol/graph-client/pull/707
- [ ] https://github.com/graphprotocol/graph-client/pull/706
- [ ] https://github.com/graphprotocol/graph-client/pull/702
- [ ] https://github.com/graphprotocol/graph-client/pull/705
- [ ] https://github.com/graphprotocol/graph-client/pull/704
- [ ] https://github.com/graphprotocol/graph-client/pull/703
- [ ] https://github.com/graphprotocol/graph-client/pull/701
- [ ] https://github.com/graphprotocol/graph-client/pull/700
- [ ] https://github.com/graphprotocol/graph-client/issues/679
```

```[tasklist]
### Tasks
```
